"""In-wall lesion meshes (calcium, lipid pool, fibrous plaque, thrombus).

A lesion is a closed, watertight, ellipsoid-like solid embedded between
the lumen surface and the outermost wall surface. The lesion mesh is
generated by deforming a unit icosphere through three local axes:

* ``u`` (axial)  -- runs along the centerline arclength,
* ``v`` (azimuth) -- runs around the lumen circumference,
* ``w`` (radial)  -- runs from the lumen outward to the adventitia.

For each vertex on the unit sphere, ``(vx, vy, vz)`` is interpreted as
``(u, v, w) in [-1, 1]^3`` and mapped to ``(s, theta, r)`` using the
lesion's ``arclength_frac``, ``azimuth_deg``, half-extents, and
``inner_offset_frac`` / ``outer_offset_frac``. The lumen radius and
total wall thickness at ``(s, theta)`` are sampled by bilinear
interpolation on the same ``(station, angle)`` grid that the lumen and
layered-wall fields share, so the lesion always sits *between* the
lumen and the outermost wall surface (never poking through).

The simulator only resolves two materials per ray (current + outer), so
a lesion mesh is rendered as a single homogeneous solid; the inner-wall
material outside the lesion mesh is what the ray returns to. This is
why we build the lesion as one closed shape and let the manifest assign
it the appropriate ``material_name`` (``calcified_plaque``,
``lipid_pool``, ``fibrous_plaque``, or ``thrombus``).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import numpy as np
import trimesh

from vesselgen.centerline import Centerline
from vesselgen.config import CalcificationLesionConfig, LESION_KIND_TO_MATERIAL
from vesselgen.cross_section import CrossSectionField
from vesselgen.wall import LayeredWallField


@dataclass
class LesionMesh:
    """A single closed-surface lesion ready for export.

    ``material_name`` is the simulator material the renderer should
    bind to this mesh (e.g. ``"calcified_plaque"``). ``name`` is a
    short slug that becomes the .obj filename stem.
    """

    name: str
    material_name: str
    mesh: trimesh.Trimesh
    config: CalcificationLesionConfig


# ---------------------------------------------------------------------------
# Geometry helpers
# ---------------------------------------------------------------------------


def _bilinear_sample(
    grid: np.ndarray,
    station_idx_f: np.ndarray,
    angle_idx_f: np.ndarray,
) -> np.ndarray:
    """Bilinear interpolation on a periodic (in angle) (N, M) grid.

    ``station_idx_f`` is clipped to ``[0, N-1]``; ``angle_idx_f`` wraps
    modulo ``M`` so any angle is valid.
    """

    n_stations, n_angles = grid.shape
    s_clip = np.clip(station_idx_f, 0.0, n_stations - 1 - 1e-9)
    s0 = np.floor(s_clip).astype(int)
    s1 = np.minimum(s0 + 1, n_stations - 1)
    fs = s_clip - s0

    a_mod = np.mod(angle_idx_f, n_angles)
    a0 = np.floor(a_mod).astype(int) % n_angles
    a1 = (a0 + 1) % n_angles
    fa = a_mod - np.floor(a_mod)

    g00 = grid[s0, a0]
    g01 = grid[s0, a1]
    g10 = grid[s1, a0]
    g11 = grid[s1, a1]

    g0 = g00 * (1.0 - fa) + g01 * fa
    g1 = g10 * (1.0 - fa) + g11 * fa
    return g0 * (1.0 - fs) + g1 * fs


def _arclength_to_station_idx(s_mm: np.ndarray, n_stations: int, length_mm: float) -> np.ndarray:
    return s_mm / max(length_mm, 1e-9) * (n_stations - 1)


def _angle_to_index(theta_rad: np.ndarray, thetas: np.ndarray) -> np.ndarray:
    """Map ``theta`` in radians to a fractional index into the periodic
    ``thetas`` grid (which spans ``[0, 2*pi)``)."""

    n_angles = thetas.shape[0]
    return np.mod(theta_rad, 2.0 * np.pi) / (2.0 * np.pi) * n_angles


def _interp_centerline(
    centerline: Centerline, s_mm: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Sample (position, normal, binormal) at arbitrary arclengths."""

    stations = centerline.stations
    s_clip = np.clip(s_mm, stations[0], stations[-1])
    i0 = np.searchsorted(stations, s_clip, side="right") - 1
    i0 = np.clip(i0, 0, len(stations) - 2)
    i1 = i0 + 1
    denom = stations[i1] - stations[i0]
    denom = np.where(denom > 0, denom, 1.0)
    t = (s_clip - stations[i0]) / denom
    t = t[:, None]

    pos = centerline.positions[i0] * (1.0 - t) + centerline.positions[i1] * t
    nrm = centerline.normals[i0] * (1.0 - t) + centerline.normals[i1] * t
    bin_ = centerline.binormals[i0] * (1.0 - t) + centerline.binormals[i1] * t
    nrm /= np.linalg.norm(nrm, axis=1, keepdims=True) + 1e-12
    bin_ /= np.linalg.norm(bin_, axis=1, keepdims=True) + 1e-12
    return pos, nrm, bin_


# ---------------------------------------------------------------------------
# Lesion mesh construction
# ---------------------------------------------------------------------------


def build_lesion_mesh(
    config: CalcificationLesionConfig,
    centerline: Centerline,
    lumen: CrossSectionField,
    wall: LayeredWallField,
    *,
    subdivisions: int = 2,
    seed: Optional[int] = None,
) -> trimesh.Trimesh:
    """Build a closed lesion mesh deformed from a unit icosphere.

    The icosphere is mapped from ``(vx, vy, vz) in unit ball`` to
    ``(axial, angular, radial)`` lesion-local coordinates, then to
    world space via the lumen + wall fields.
    """

    sphere = trimesh.creation.icosphere(subdivisions=subdivisions, radius=1.0)
    verts = sphere.vertices.copy()
    faces = sphere.faces.copy()

    rng = np.random.default_rng(seed if seed is not None else config.seed)

    length_mm = float(centerline.length_mm)
    half_axial_mm = 0.5 * float(config.axial_extent_mm)
    half_arc_rad = 0.5 * float(np.deg2rad(config.arc_extent_deg))
    azimuth_rad = float(np.deg2rad(config.azimuth_deg))
    s_center_mm = float(config.arclength_frac) * length_mm
    inner_frac = float(config.inner_offset_frac)
    outer_frac = float(config.outer_offset_frac)
    radial_mid = 0.5 * (inner_frac + outer_frac)
    radial_half = 0.5 * (outer_frac - inner_frac)

    bumpiness = 0.10
    if subdivisions > 1:
        bump = 1.0 + bumpiness * (rng.random(verts.shape[0]) - 0.5)
        verts = verts * bump[:, None]

    u = verts[:, 0]
    v = verts[:, 1]
    w = verts[:, 2]

    s_mm = np.clip(s_center_mm + half_axial_mm * u, 0.0, length_mm)
    theta_rad = azimuth_rad + half_arc_rad * v
    radial_frac = radial_mid + radial_half * w

    n_stations = lumen.n_stations
    n_angles = lumen.n_angles
    s_idx_f = _arclength_to_station_idx(s_mm, n_stations, length_mm)
    a_idx_f = _angle_to_index(theta_rad, lumen.thetas)

    lumen_r = _bilinear_sample(lumen.radii, s_idx_f, a_idx_f)
    outer_r = _bilinear_sample(wall.interface_radii[-1], s_idx_f, a_idx_f)
    total_wall = np.maximum(outer_r - lumen_r, 1e-6)

    radial_frac = np.clip(radial_frac, 0.005, 0.995)
    r = lumen_r + radial_frac * total_wall

    pos, normal, binormal = _interp_centerline(centerline, s_mm)
    cos_t = np.cos(theta_rad)[:, None]
    sin_t = np.sin(theta_rad)[:, None]
    world = pos + (r[:, None] * cos_t) * normal + (r[:, None] * sin_t) * binormal

    mesh = trimesh.Trimesh(vertices=world, faces=faces, process=True)
    if not mesh.is_watertight:
        mesh.fill_holes()
    # The frame's (normal, binormal, tangent) basis can be left-handed
    # relative to the original sphere's (x, y, z), so the deformation
    # sometimes inverts face winding. Re-orient so outward normals point
    # away from the lesion centroid (the same convention sweep.py uses).
    if mesh.volume < 0.0:
        mesh.invert()
    return mesh


def build_all_lesions(
    configs: list[CalcificationLesionConfig],
    centerline: Centerline,
    lumen: CrossSectionField,
    wall: LayeredWallField,
    *,
    name_prefix: str = "lesion",
) -> list[LesionMesh]:
    """Build :class:`LesionMesh` records for every config in ``configs``."""

    results: list[LesionMesh] = []
    for i, cfg in enumerate(configs):
        mesh = build_lesion_mesh(cfg, centerline, lumen, wall)
        material_name = LESION_KIND_TO_MATERIAL[cfg.kind]
        results.append(
            LesionMesh(
                name=f"{name_prefix}_{i:02d}_{cfg.kind}",
                material_name=material_name,
                mesh=mesh,
                config=cfg,
            )
        )
    return results
